### ISSUE TITLE
BRIDGE_USER in the Hue sample

### ISSUE THREAD

**Issue by nosaturn** [CiscoDevNet/xapi-samples#5]
I may be dumb, but how do i find/generate BRIDGE_USER?

**Comment by ObjectIsAdvantag** [comment]
hi @nosaturn , there's no dumb question, happy to help.
the bridge user is the unique identifier of the user you'll create when configuring your Hue bridge.
To me it would be more of a secret but user is how the Hue documentation refers to it.
Here is the Hue getting started tutorial that explains how to generate the username
https://developers.meethue.com/develop/get-started-2/

Look for this section in the doc:
> Congratulations you’ve just created an authorized user (1028d66426293e821ecfd9ef1a0731df), which we’ll use from now on!

**Comment by nosaturn** [comment]
alright that got it :)
well sorta. I ended up using HUE Essentials on my Android to generate a working user id number because the instructions there simply were not working. the get and post commands didn't return anything.
but i used the HUE Essentials to generate a new apps and username, plugged it into the script and it's working. plus i see it on the HUE website for my profile.

**Comment by nosaturn** [comment]
(didn't realize i was actually opening a issue issue... obviously this wasn't a code issue.
now i just gotta figure our how to make the panel a little fancier and perhaps activate scenes. and maybe a flash the lights when a call comes in or turn on a light while in a meeting (in a call light).

**Comment by ObjectIsAdvantag** [comment]
hi @nosaturn, glad you made it, and thanks for the tip / guidance above.

also, I would invite you to check the onair code sample,
https://github.com/CiscoDevNet/xapi-samples/tree/master/controls/onair

there is also a hue_disco proposed that flashes the lights with timers.
